### ISSUE TITLE
Double quotes in labels

### ISSUE THREAD

**Issue by lexjansen** [dostiep/Dataset-JSON-SAS#1]
In the event that dataset or variable labels contain double quotes, the stylesheet does not processes these correctly.
It can be easily solved by using the quote function in SAS:

write values &quot;label&quot; %sysfunc(quote(</xsl:text> <xsl:value-of select="$Label"/> <xsl:text>));</xsl:text>

Nice solution!

**Comment by dostiep** [comment]
Thanks Lex, I fixed the issue.
